steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        PROJECT_ID="gcds-oht33435u3-2023"
        DATASET="${_DATASET}"
        MASTER_TABLE="Fake_data"
        NEW_TABLE="my_table"
        
        # Step 1: Create a new table from a master table
        bq cp $PROJECT_ID:$DATASET.$MASTER_TABLE $PROJECT_ID:$DATASET.$NEW_TABLE

        # Step 2: Make schema changes to the new table
        bq query --use_legacy_sql=false "ALTER TABLE $PROJECT_ID:$DATASET.$NEW_TABLE DROP COLUMN IF EXISTS Address"

        # Step 3: Compare the schema
        bq show --schema --format=prettyjson $PROJECT_ID:$DATASET.$MASTER_TABLE > master_schema.json
        bq show --schema --format=prettyjson $PROJECT_ID:$DATASET.$NEW_TABLE > new_schema.json
        diff -q master_schema.json new_schema.json > /dev/null || exit 0
options:
 logging: CLOUD_LOGGING_ONLY
