steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
substitutions:
        _MYDATASET=Ideathon_gcp
        _MY_MASTER_TABLE=Fake_data
        _NEWTABLE=my_table
        
        # Step 1: Create a new table from a master table
        bq cp $PROJECT_ID:$_MYDATASET.$_MYMASTER_TABLE $PROJECT_ID:$_MYDATASET.$NEW_TABLE

        # Step 2: Make schema changes to the new table
        bq query --use_legacy_sql=false "ALTER TABLE $PROJECT_ID:$_MYDATASET.$_NEWTABLE DROP COLUMN IF EXISTS Address"

        # Step 3: Compare the schema
        bq show --schema --format=prettyjson $PROJECT_ID:$_MYDATASET.$_MYMASTER_TABLE > master_schema.json
        bq show --schema --format=prettyjson $PROJECT_ID:$_MYDATASET.$_NEWTABLE > new_schema.json
        diff -q master_schema.json new_schema.json > /dev/null || exit 0
options:
 logging: CLOUD_LOGGING_ONLY
