steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        git clone https://github.com/gcpbytewizards/Devops_usecase.git
        cd Devops_usecase
        git checkout $BRANCH_NAME

  # Step 2: Check changes in the folder
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |        
        git diff --name-status $last_commit_sha $current_commit_sha -- airflow_code/ | while read status file; do
          if [ "$status" == "D" ]; then
            echo "File $file deleted in the current commit"
            # Remove the file from the GCS bucket
            gsutil rm gs://_COMPOSER_BUCKET/$file
          elif [ "$status" == "M" ] || [ "$status" == "A" ]; then
            echo "File $file modified or added in the current commit"
            # Upload the file to the GCS bucket
            gsutil cp $file gs://_COMPOSER_BUCKET/$file
          else
            echo "File $file has unknown status $status in the current commit"
          fi
        done

substitutions:
  BRANCH_NAME: main
  last_commit_sha: FETCH_HEAD
  current_commit_sha: HEAD

options:
  logging: CLOUD_LOGGING_ONLY

