  # Step 1: Check changes in the folder
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        # Find changed files and process them one by one
          status="$(git diff --name-status $_LAST_COMMIT $_CURRENT_COMMIT  airflow_code/* |  grep -E '^(M|A|D)' | cut -f1)" &&
          file="$(git diff --name-status $_LAST_COMMIT $_CURRENT_COMMIT  airflow_code/* |  grep -E '^(M|A|D)' | cut -f2- | sed 's,^airflow_code/,,g' | xargs -I {} sh -c 'echo {}')" &&
          if [ "$status" == "D" ]; then
            echo "File $file deleted in the current commit"
            # Remove the file from the GCS bucket
            gsutil rm gs://_COMPOSER_BUCKET/$file
          elif [ "$status" == "M" ] || [ "$status" == "A" ]; then
            echo "File $file modified or added in the current commit"
            # Upload the file to the GCS bucket
            gsutil rm gs://_COMPOSER_BUCKET/$file
            gsutil cp airflow_code/$file gs://_COMPOSER_BUCKET/$file
          else
            echo "File $file has unknown status $status in the current commit"
          fi

substitutions:
  _LAST_COMMIT: FETCH_HEAD
  _BRANCH_NAME: main
  _CURRENT_COMMIT: HEAD

options:
  logging: CLOUD_LOGGING_ONLY

