steps:
  # Step 1: Check changes in the folder
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        # Find changed files and process them one by one
        status="$(git diff --name-status $_LAST_COMMIT $_CURRENT_COMMIT airflow_code/* | grep -E '^(M|A|D)' | cut -f1)" &&
        file="$(git diff --name-status $_LAST_COMMIT $_CURRENT_COMMIT airflow_code/* | grep -E '^(M|A|D)' | cut -f2- | sed 's,^airflow_code/,,g' | xargs -I {} sh -c 'echo {}')" &&
        echo "Status: $status"
        echo "File: $file" > /workspace/output.txt

  # Step 2: Process the changes using gcloud commands
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        # Read the output from the previous step
        file=$(cat /workspace/output.txt)
        while IFS= read -r line; do
          if [ "$line" == "Status: D" ]; then
            echo "File $file deleted in the current commit"
            # Remove the file from the GCS bucket
            gsutil rm gs://_COMPOSER_BUCKET/$file
          elif [ "$line" == "Status: M" ] || [ "$line" == "Status: A" ]; then
            echo "File $file modified or added in the current commit"
            # Upload the file to the GCS bucket
            gsutil rm gs://_COMPOSER_BUCKET/$file
            gsutil cp airflow_code/$file gs://_COMPOSER_BUCKET/$file
          else
            echo "File $file has an unknown status $line in the current commit"
          fi
        done < output.txt

substitutions:
  _LAST_COMMIT: FETCH_HEAD
  _BRANCH_NAME: main
  _CURRENT_COMMIT: HEAD

options:
  logging: CLOUD_LOGGING_ONLY


